CLIENT_ID = "1090257689817-qe52ioolbtr7vtkrpgjdnps5e583cq46.apps.googleusercontent.com"
CLIENT_SECRET = "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"
FLASK_SECRET_KEY = "a_very_random_and_strong_secret_key_here" # Change this in production!